### PR TITLE
fix wrong result in truncate table

### PR DESCRIPTION
**Pull request by nautaa**
`truncate table` doesn't change the `PartStore` metadata. So if we `truncate table` and `insert into table`, we will get the wrong result.
This PR makes it right.

### CODE REVIEW

**Comment by jinmingjian** [comment]
@nautaa really appreciated for your careful examining! For the time limitation in that coding time, I "skip" the truncate command.

**Comment by jinmingjian** [comment]
@nautaa Is it possible to add a simple and great test in sanity integ tests like [tests_integ_stress_test_ddl](https://github.com/tensorbase/tensorbase/blob/ffcf44a378c28d65ee32bc99690ab4d86cc0cbd9/crates/tests_integ/tests/sanity_checks.rs#L17)?

**Comment by nautaa** [comment]
> @nautaa Is it possible to add a simple and great test in sanity integ tests like [tests_integ_stress_test_ddl](https://github.com/tensorbase/tensorbase/blob/ffcf44a378c28d65ee32bc99690ab4d86cc0cbd9/crates/tests_integ/tests/sanity_checks.rs#L17)?

Integ tests have added.

**Comment by jinmingjian** [comment]
@nautaa thanks for your great contribution! I enrich the stress for ddl. Let's do more great things!

**Comment by jinmingjian** [comment]
@nautaa this fix has a stupid mistake at clear method. This is my mistake for skipping review:)

If you want to fix this, just sumbit a new PR. Still thanks!

**Pull request merged**
