### PR TITLE
Allow trailing semicolon in sql stmt

### LINKED ISSUE #107: allow trailing semicolon in sql statement

### PR DESCRIPTION
**Pull request by chenyukang**
close #107

### CODE REVIEW

**Comment by jinmingjian** [comment]
@chenyukang  this PR is your first contribution. So, the test action will not be started automatically. It is better to make sure your commit working locally.

**Comment by chenyukang** [comment]
Ok, I use this command to run locally:
```
cargo test --exclude 'arrow*' --exclude datafusion --exclude 'ballista*' --exclude parquet --workspace -- --test-threads=1 --skip tests_integ  -- --show-output test_trailing_semicolon_in_sql_stmt
```

**Comment by jinmingjian** [comment]
@chenyukang no problem. And you can use the unit test in your IDE. To run the lang's unit tests are enough for primary checking.

**Comment by jinmingjian** [comment]
it seems the solution#1 works:)

**Pull request merged**
