### PR TITLE
[Summer 2021] Draft design for MySQL Protocol Server

### PR DESCRIPTION
**Pull request by fandahao17**
This is a draft design for the MySQL protocol server of my Summer 2021 project (#149). It still fails some tests and lacks some features. But it is ready for discussion.

The major challenge for our MySQL protocol server is that TensorBase's runtime was built with ClickHouse as its only frontend. So **1)** its runtime is tightly coupled with ClickHouse's protocol server implementation, e.g., the code in `runtime` crate uses `Block` and `Column` in the `ch` module to represent data. **2)** Some data encoding are in ClickHouse's format (e.g., `BaseChunk`), which is different from MySQL's encoding scheme.

For these problems, my approach is to decouple TensorBase's runtime as much as possible with ClickHouse's frontend. **1)** I use Arrow's `Array` to represent columnar data, instead of the original `BaseChunk`. This is because `BaseChunk` only exposes its data as `Vec<u8>`, which makes it hard and buggy to do element-wise data access. As we do data conversion between different protocols, element-wise data access becomes important. Moreover, `BaseChunk` seems to use Arrow's data format. So `BaseChunk` and Arrow's `Array` are essentially the same but the latter has richer features. **2)** In the same way, I use Arrow's `RecordBatch` to represent block data, in place of the original `Block`. 

But I'm confused about our early design decisions: It seems that `BaseChunk`(`Column`) and `Block` are our simplified version of `Array` and `RecordBatch`. We added a lot of code for byte access based on `BaseChunk`, and I believe a lot of debugging efforts are put in it. Why did we choose to use them instead of Arrow's implementation? Was it for performance issues? 

Based on the above changes, I wrote a shim layer with the current `server_mysql` crate. I also added an async MySQL server and client implementation. Now it is able to execute the following simple queries:

``` sql
CREATE DATABASE IF NOT EXISTS test
USE test
DROP TABLE IF EXISTS test_tab
CREATE TABLE test_tab(foo UInt64)
INSERT INTO test_tab VALUES (1), (2), (3)
select foo from test_tab
select sum(foo) from test_tab
```

A few things need to be done before this draft design is ready to be merged:

- [ ] Fix the bugs that cause integ_checks to fail. 
- [ ] Decide if we still need `Block` and `BaseChunk`s. Now I kept them so I make minimum change of code. If we do find the byte access complexity outweigh their benefits, I can completely remove them.
- [ ] Add support for Datatime, Date, Decimal and String data types.
- [ ] Add support for InsertFormatInline and InsertFormatCSV methods.
- [ ] Add integration tests for the MySQL server.

### CODE REVIEW

**Comment by jinmingjian** [comment]
@fandahao17 I see we pass all the tests. Is this appropriate to merge the current PR as first come-out? We can gradually solve all other tasks listed by you here.

**Comment by fandahao17** [comment]
Hi, @jinmingjian. It's still not ready now because I intentionally deleted one test to see where the error happens😄. I'm still working hard to locate the bug.

**Comment by fandahao17** [comment]
BTW, could you please give your opinions on whether my decision to replace BaseChunk with Arrow's RecordBatch is feasible?

**Comment by jinmingjian** [comment]
@fandahao17 it is ok to use Arrow's RecordBatch rather than BaseChunk. We have made Block and RecordBatch convertable by Into trait. And the conversion between them is cheap. I have not reviewed your PR in detail. But basically, the idea has no problem. Finally, thanks for your works!

**Comment by fandahao17** [comment]
UPDATE: I've been investigating this memory error over the last two weeks. It seems to be cause by some problem with the jemalloc allocator. My LLDB tracing shows that some realloc's would overwrite the contents of other unrelated variable. Switching off jemalloc makes all the tests pass.

This finding is quite surprising. I will continue to investigate the root cause.

**Comment by jinmingjian** [comment]
> UPDATE: I've been investigating this memory error over the last two weeks. 

Not sure what is your memory error? which one test did you deleted?  JE is in-production option. It could be more possible that glibc's malloc has more problem, in my experience.

**Comment by fandahao17** [comment]
I continued to look into this problem and solved it today. It is caused by my improper understanding of Arrow's Buffer::from_raw_parts method. Now all the tests passed. But I think my current code is a bit messy. Should I reorganize my code and split this PR into several smaller PRs? (e.g., refactoring, new feature)

Just in case you are curious, the memory error occurs when I convert CH client's `ServerBlock` into `RecodBatch`:

``` rust
fn serverblock_to_recordbatch(b: ServerBlock) -> BaseRtResult<RecordBatch> {
    ...
    let data = unsafe { c.data.into_bytes() }; // c is a column of b

    let data_len = data.len();
    // data_cap is the capacity of the Vec<u8>, 
    // which doesn't necessarily equal to the amount of memory allocated for the vector
    let data_cap = data.capacity(); 
    let data_addr = data.as_ptr();

    let buf = unsafe {
        let ptr = NonNull::new(data_addr as *mut u8).unwrap();
         // from_raw_parts needs to know the exact allocation size for the memory buffer
        Buffer::from_raw_parts(ptr, data_len, data_cap)
    };   
    ...
}
```

**Comment by jinmingjian** [comment]
> I continued to look into this problem and solved it today. It is caused by my improper understanding of Arrow's Buffer::from_raw_parts method.

Great to know the good catch. You have done a good learning in unsafe side. 

> Should I reorganize my code and split this PR into several smaller PRs?

This is recommended. You can submit the works in the granularity of the task , not necessary all-in -one.  And this makes the review life easier:)

**Comment by fandahao17** [comment]
OK. I'll close this PR and submit the sub-PR's soon

**Pull request closed without merging**
