### PR TITLE
FEAT(runtime): support primary key data deduplication

### PR DESCRIPTION
**Pull request by nautaa**
Signed-off-by: nautaa <870284156@qq.com>
relate issue: #266
This PR supports primary key data deduplication. 
primary key type:
* UInt8/UInt16/UInt32/UInt64
* Date
* DateTime
* FixString

Taking into account the consistency of pk meta, the method of metadata reconstruction from data is adopted.
- [x] Other data types.
- [x] The recovery of PK metadata from disk.

### CODE REVIEW

**Comment by jinmingjian** [comment]
@nautaa Happy Mid-Autumn Festival :full_moon:

**Comment by nautaa** [comment]
it is ready for review.

**Comment by jinmingjian** [comment]
@nautaa really thanks for this PR.  I will review your interesting implementation in it. You've done great achievement in this summer. Congratulations!

**Comment by jinmingjian** [comment]
I have reviewed the PR. In fact, this PR is far away from the original design. Furthermore, this solution is naive for the industrial usage. Considering the current state of this project, I close this PR. For someone to continue to this effort, just reach me in the community. Still thanks @nautaa 's contributions!

**Pull request closed without merging**
