### PR TITLE
REFACTOR(datafusion): extract clickhouse functions in datafusion to a separate enum

### PR DESCRIPTION
**Pull request by whjpji**
Signed-off-by: Frank King <frankking1729@gmail.com>

As the discussion in #130, this PR is intended to separate CH functions from DF functions for extensibility, and enable CH functions to be case-sensitive.

### CODE REVIEW

**Comment by jinmingjian** [comment]
@whjpji this is a feat! :rocket:  Let's do a check.

**Comment by jinmingjian** [comment]
@whjpji I will do some primary checks for this PR for if the optimizer works normally.

**Comment by jinmingjian** [comment]
@whjpji can you move all changes to datafusion to a dedicated commit? In the future, we want all changes to A-DF crates in dedicated one commit.

**Comment by whjpji** [comment]
> @whjpji can you move all changes to datafusion to a dedicated commit? In the future, we want all changes to A-DF crates in dedicated one commit.

As for this PR, it is already a single commit. Do you mean to squash the commits about DF including PR #146 into a single one? I'm afraid not, because I have no write access to modify the submitted commits.

Nevertheless, I can do this rebase, and then you help me to submit it.

**Comment by whjpji** [comment]
@jinmingjian I have done the rebase, and after that, my commit is before yours, so there will be conflicts.

**Comment by whjpji** [comment]
There seems to be some conflicting files, let me rebase it again by cherry-pick.

**Comment by whjpji** [comment]
Oh! It is not easy to avoid the conflicts in these two files. It is probably because of the squashed four commits.

You might better be careful to resolve the conflicts, or should I undo all rebases and reset it to the earlier version?

**Comment by jinmingjian** [comment]
@whjpji let me have a look. thanks!

**Comment by jinmingjian** [comment]
@whjpji you mess up the new commits with your own PR. Could you reset this PR to your early one(before rebase)?

**Comment by whjpji** [comment]
> @whjpji you mess up the new commits with your own PR. Could you reset this PR to your early one(before rebase)?

Done.

**Comment by jinmingjian** [comment]
@whjpji thanks. serveral tips:
1. ```git rebase main``` to make your branch on the tip of main
2. ```git reset --soft HEAD~``` to make head commit back to the stage, then you can reorganize your commit as you like.

**Comment by whjpji** [comment]
Oh! There's still conflicts. Maybe you should resolve it manually.

**Comment by jinmingjian** [comment]
@whjpji ok, thanks! No rush, and have a good night!

**Comment by jinmingjian** [comment]
The way is to wrap a new enum variant in the original enum. It is good. And currenty, there are not too much fn-level opt. There will be type ser/de problem when billista come in, but we solve it when it come.

**Pull request merged**
