### PR TITLE
FEAT(parse, runtime): support primary key parse

### PR DESCRIPTION
**Pull request by nautaa**
Signed-off-by: nautaa <870284156@qq.com>

relate issue: #266

### CODE REVIEW

**Comment by nautaa** [comment]
Is this wrong with CI?

**Comment by fandahao17** [comment]
Same problem occurred on my fork.

The [packed_simd_2](https://github.com/rust-lang/packed_simd) crate depended by Arrow recently released a new version. The new version seems to [use a feature](https://github.com/rust-lang/packed_simd/commit/45d5347a0d2187c046a546a477d2a53111cd7713) from a newer Nightly version.

**Comment by jinmingjian** [comment]
@fandahao17 good catch! Can you send out a PR for this?:)

**Comment by fandahao17** [comment]
Sure, I'll work on this.

**Pull request merged**
