### PR TITLE
support CH functions toMonth, toDayOfMonth

### PR DESCRIPTION
**Pull request by whjpji**
Signed-off-by: Frank King <frankking1729@gmail.com>

#131 

- [ ] Add more test cases and sanity checks

### CODE REVIEW

**Comment by whjpji** [comment]
Hi @jinmingjian, I have enabled the unit tests in DF, and there are many failures due to `UTF8` v.s. `LargeUTF8` matters, such as
```
---- sql::planner::tests::select_simple_aggregate_with_groupby_and_column_in_group_by_does_not_exist stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"Plan(\"Invalid identifier \\'doesnotexist\\' for schema id, first_name, last_name, age, state, salary, birth_date, 😀\")"`,
 right: `"Plan(\"Invalid identifier 'doesnotexist' for schema id, first_name, last_name, age, state, salary, birth_date, 😀\")"`', crates/datafusion/src/sql/planner.rs:2289:9

---- sql::planner::tests::select_simple_filter stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"Projection: #id, #first_name, #last_name\n  Filter: #state Eq Utf8(\"CO\")\n    TableScan: person projection=None"`,
 right: `"Projection: #id, #first_name, #last_name\n  Filter: #state Eq LargeUtf8(\"CO\")\n    TableScan: person projection=None"`', crates/datafusion/src/sql/planner.rs:3180:9

---- sql::planner::tests::select_typedstring stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"Projection: CAST(Utf8(\"2020-12-10\") AS Date16) AS date\n  TableScan: person projection=None"`,
 right: `"Projection: CAST(LargeUtf8(\"2020-12-10\") AS Date16) AS date\n  TableScan: person projection=None"`', crates/datafusion/src/sql/planner.rs:3180:9
```
Could you please help me check these errors?

**Comment by jinmingjian** [comment]
@whjpji really coo! You goes into the macro world and help us on more abstractions!

**Comment by jinmingjian** [comment]
> Hi @jinmingjian, I have enabled the unit tests in DF, and there are many failures due to `UTF8` v.s. `LargeUTF8` matters, such as

@whjpji this is because you remove the "--exclude datafusion" in unit checks. Our string is not same to the raw string in DataFusion. We have have varint encoding head in the string because of the CH uses this string schema.

I suggest we temporarily still skip all tests in datafusion now. In the future, there are two ways to solve this problem. One in writing time, other is in querying time. How do you think which side is good?

**Comment by jinmingjian** [comment]
I used the CH string as a quick workaround. It seems a problem for general understanding, I think we should resolve this ASAP.

**Comment by whjpji** [comment]
> > Hi @jinmingjian, I have enabled the unit tests in DF, and there are many failures due to `UTF8` v.s. `LargeUTF8` matters, such as
> 
> @whjpji this is because you remove the "--exclude datafusion" in unit checks. Our string is not same to the raw string in DataFusion. We have have varint length encoding head in the string because of the CH uses this string schema. So a string in TB, is like this: "abc" -> "{3}abc".
> 
> I suggest we temporarily still skip all tests in datafusion now. In the future, there are two ways to solve this problem. One in writing time, other is in querying time. How do you think which side is good?

I think skipping all tests in DF might not be a good idea because we are adding new functions into DF, and these functions need to be tested. In alternative, can we temporarily disabled DF tests except those in `ch_fns`?

**Comment by jinmingjian** [comment]
@whjpji great awareness. this needs some exploring:)

**Comment by jinmingjian** [comment]
@whjpji I have a suggestion: move out all that our customized tests case to a dedicated crate, such as datafusion_tests which can depend on the datafusion. How about this?

**Comment by jinmingjian** [comment]
@whjpji thanks for great refactoring. One problem, you do too much formatting in ```crates/datafusion/src/physical_plan/functions.rs```. This will cause big headache when I update the DataFusion. So the principle to change Arrow and DataFusion sources is to keep all the change minimized, even all the formatting.

**Comment by whjpji** [comment]
> @whjpji thanks for great refactoring. One problem, you do too much formatting in `crates/datafusion/src/physical_plan/functions.rs`. This will cause big headache when I update the DataFusion. So the principle to change Arrow and DataFusion sources is to keep all the change minimized, even all the formatting.

OK, I will disable the IDE's automatic formatting and revert those changes.

**Comment by jinmingjian** [comment]
@whjpji Base community thanks for your this great contribution! I do a small rebase for letting all changes to A-DF in one commit.

**Review by jinmingjian — APPROVED** [review]
let's check-in

**Comment by jinmingjian** [comment]
It seems the rebase work makes your contribution trace disappeared. Bad! Let's keep this in mind for future PRs!

**Comment by whjpji** [comment]
> It seems the rebase work makes your contribution trace disappeared. Bad! Let's keep this in mind for future PRs!

Yes, the next time you can specify the author when committing by `git commit --author="Somebody <email@example.com>"`

**Comment by jinmingjian** [comment]
Cool! let me to see if I can amend that commit.

**Pull request merged**
