### PR TITLE
FIX(version): use newer Nightly version

### PR DESCRIPTION
**Pull request by fandahao17**
This change is made because a newer release of one of our dependencies uses some rustc feature from a newer Nightly version (#267).

This Nightly version (2021-09-01) is carefully selected because newer Nightly versions will [cause errors in the `Itertools` crate](https://github.com/rust-itertools/itertools/pull/576#issuecomment-917349982).

### CODE REVIEW

**Comment by fandahao17** [comment]
Besides this change, I'd recommend we put `Cargo.lock` into git to lock our dependencies, so we won't have to worry about such problems any more.

[The Cargo Book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html) recommends checking `Cargo.lock` into git for binary crates.

**Comment by jinmingjian** [comment]
@fandahao17 ```Cargo.lock``` makes the development more ossified. And sometimes, you miss some updates in the language and dependencies. ```Cargo.lock``` solves this problem lock the progress.  You still have to fix all the problem if you want to progress. Our philosophy should be to fix it ASAP, not to hide the ears and steal the bells.

Is it possible to disable some tests in sanity_checks_mysql to make ```Base Integ Sanity Checks``` passed?

**Comment by fandahao17** [comment]
I disabled one test. Now CI passed.

**Comment by jinmingjian** [comment]
@fandahao17 thanks. Although, your new test cases disabled, we do not introduce new regression at least.

**Pull request merged**
