### PR TITLE
REFACTOR(datafusion): simplify the `wrap_datetime_fn` macro

### PR DESCRIPTION
**Pull request by whjpji**
@jinmingjian @pandaplusplus 
After #173, the macros in `clickhouse.rs` in A-DF shows to become too complicated. So I simplified the wrapping macro to contain only a array downcast process.

### CODE REVIEW

**Comment by jinmingjian** [comment]
@whjpji this PR reduces boilerplate, and KISS, I really like this!

**Comment by whjpji** [comment]
I think other two macros `def_datetime_fn` and `wrap_string_fn` can be simplified in a similar way, to wrap only the inner layer, instead of the whole function's definition.

I will continue to do this work and may add more commits.

**Comment by pandaplusplus** [comment]
I couldn't agree more. We need a simple and clear macro template that can be modeled later.

**Comment by jinmingjian** [comment]
@whjpji we put too many additions in this PR. If tests passed, I will merge this PR firstly.

**Comment by whjpji** [comment]
@jinmingjian I have moved `chickhouse::str_to_u16` to `base` and named `parse_to_days`.

BTW, After the refactory, Only `LargeUtf8` is allowed to begin with a length on its bytes representation, because the `toDate` function is only called by us in purpose of keeping compatibility with CH.

**Comment by jinmingjian** [comment]
@whjpji nice refactoring!

**Pull request merged**
